version: "3"

services:
  php-build:
    build:
      context: .
      dockerfile: Dockerfile
    image: pixlmint/php-server:8.2
    ports:
      - 88:80
    container_name: php-build
    volumes:
      - ./:/var/www/html


